### ISSUE TITLE
[todo] 160818

### ISSUE THREAD

**Issue by havefuncoding** [havefuncoding/gitProjects#13]
**Week**: we160814, https://github.com/havefuncoding/gitProjects/issues/12
**Note**: adding daily helpers to better manage tasks

08/18 TH:
---

- [x] explicitly assigned tasks, tbd ** [c**]
- [x] continue refactor tests 2 weeks+ stale
- [ ] replace mock function with actual before method annotation
- [ ] update loyalty test with login and linked card features
- [ ] linkedlist: https://leetcode.com/problems/reverse-linked-list/
- [ ] 5 where Difficulty="Easy", https://www.hackerrank.com/domains/data-structures/arrays
- [ ] 12 where Difficulty="Easy", https://www.hackerrank.com/domains/java/java-introduction
- [x] wikipedia/relevant daily 45 min.
- [x] touch typing daily 25 min.

**Comment by havefuncoding** [comment]
trouble with @beforeMethod / running as suite:

![inconsistentwhenrunassuite](https://cloud.githubusercontent.com/assets/10410748/17785047/088eed04-6534-11e6-8305-ff812f1f5c61.jpg)

**Comment by havefuncoding** [comment]
**moved to Friday, 160819, https://github.com/havefuncoding/gitProjects/issues/14**
- [ ] replace mock function with actual before method annotation ** **_in progress_** **
- [ ] update loyalty test with login and linked card features
- [ ] linkedlist: https://leetcode.com/problems/reverse-linked-list/
- [ ] 5 where Difficulty="Easy", https://www.hackerrank.com/domains/data-structures/arrays

**note**: explicitly assigned tasks took higher priority and consumed more time than expected
