### ISSUE TITLE
[todo] 160819

### ISSUE THREAD

**Issue by havefuncoding** [havefuncoding/gitProjects#14]
**Week**: we160814, https://github.com/havefuncoding/gitProjects/issues/12

08/19 FR:
---

- [ ] explicitly assigned tasks, tbd **
- [ ] replace mock function with actual before method annotation
- [ ] python db course week 5 assignment
- [ ] insert weekly deals into sqlite using python
- [ ] 5 where Difficulty="Easy", https://www.hackerrank.com/domains/data-structures/arrays
- [ ] 12 where Difficulty="Easy", https://www.hackerrank.com/domains/java/java-introduction
- [ ] wikipedia/relevant daily 45 min.
- [ ] touch typing daily 25 min.

**Comment by havefuncoding** [comment]
sticking with weekly instead daily
