### ISSUE TITLE
[todo] 160820

### ISSUE THREAD

**Issue by havefuncoding** [havefuncoding/gitProjects#15]
**Week**: we160814, https://github.com/havefuncoding/gitProjects/issues/12

08/20 SA:
---

- [ ] grab just basic data using sqlite browser and python
- [ ] linkedlist: https://leetcode.com/problems/reverse-linked-list/
- [ ] tree: https://leetcode.com/problems/same-tree/
- [ ] http://www.tutorialspoint.com/java/java_data_structures.htm
- [ ] script to log issue using Github API
- [ ] wikipedia/relevant daily 45 min.
- [ ] touch typing daily 25 min.

**Comment by havefuncoding** [comment]
sticking with weekly instead daily
